#%RAML 1.0 DataType

type: object 
properties:
  ID: integer
  airline: string
  code: string
  price: integer
  departureDate: date-only
  departureTime: time-only
  arrivalTime: time-only
  totalDuration: string
  origin : string
  destination: string