#%RAML 1.0 NamedExample

-
  ID: 1 
  airline: spicejet
  code: ER38sd
  price: 400
  departureDate: 2015-05-23
  departureTime: 20:19:00
  arrivalTime: 20:19:00
  totalDuration: 2h 33h
  origin: PUN
  destination: MUM
  

-
  ID: 2
  airline: spicejet
  code: ER37as
  price: 407
  departureDate: 2015-05-23
  departureTime: 20:19:00
  arrivalTime: 20:19:00
  totalDuration: 2h 33h
  origin: DEL
  destination: PUN
  
