#%RAML 1.0 NamedExample

passengerDetails:
  firstName: Tom
  lastName: Cruise
  age: 48
  gender: Male
  contactDetails: 
   mobileNumber: 62379239
   emailID: tomcruise@gmail.com
flightDetails:
  code: ER38sd
  airline: spicejet
  price: 400
  departureDate: 2015-05-23
  departureTime: 20:19:00
  arrivalTime: 20:19:00
  totalDuration: 2h 33h
  origin: PUN
  destination: MUM
  plane:
    classType: economy
    seatsAvailable: 150


